package org.example.apsconsumodeagua.utils.enums;

public enum ToastEnum {
    ALERT, SUCESSO, ERRO,CENTRO,CENTRO_TOPO,CENTRO_BAIXO,CENTRO_DIREITA,CENTRO_ESQUERDA,TOPO_ESQUERDA,TOPO_DIREITA,BAIXO_ESQUERDA,BAIXO_DIREITA
}
